Fix get_param_str in fjage.c
org-arl/fjage pull request #264
Opened 2023-01-09 04:15 UTC by notthetup

This is a bug fix for a bug in `fjage.c` where `fjage_get_param_str` causes a null pointer to be returned even if there is a valid string available.

The reason is : 

https://github.com/org-arl/fjage/blob/master/gateways/c/src/fjage.c#L1365..L1366
`v = fjage_msg_get_string(msg, "value");`
`v` is a pointer into the message's body to the string..
And then we free the message body with `fjage_msg_destroy(msg);`
So `v` is now pointing into freed memory?

2023-01-10 06:53 UTC, mchitre commented
This is a BREAKING change, since it changes the API and leads to memory leaks for all previous users of fjåge! We need to tag the release as such and mention it clearly in the release notes. Are there any other APIs we need to break? If so, we should do it at the same time.

2023-01-10 10:13 UTC, notthetup commented
True. I am not sure if there are any other breaking changes pending for the fjage.c Gateway.

P.S. Also happy to change this fix in a way that doesn't break the API, but I couldn't think of any other approach.

2023-01-10 23:43 UTC, notthetup commented
I do prefer that style of API. It makes memory ownership more transparent. But that'll also be a breaking change.

Also, if that's the approach we're going for, we should use that style across the board for other APIs which return pointers etc.

2023-01-11 17:20 UTC, mchitre commented
It's better breaking, in the sense that it'll fail at compilation and force a user to make changes with understanding. The other breaking is dangerous as the compilation will succeed and they'll get memory leaks silently.

2023-01-14 10:24 UTC, mchitre requested changes
Requested changes as per discussion on the PR

2023-03-13 02:51 UTC, mchitre approved these changes
Might want to consider adding test cases for checking that it returns required buffer size correctly if NULL is passed in.

2023-03-13 04:13 UTC, notthetup commented
If `NULL` is passed in for `const char* strval`, then ideally it shouldn't copy ANY characters into the buffer. In such a scenario, should it return `0`?

2023-03-13 05:22 UTC, mchitre commented
It should return the actual length so user knows what size buffer needs to be passed in.

2023-03-15 06:55 UTC, mchitre approved these changes

2023-03-15 07:46 UTC, merged